apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default (printf "%s-tea" (include "fullname" .)) }}
  food: {{ quote .Values.favorite.food }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: true
  {{- end }}